### ISSUE TITLE
GetCommits can exclude commits in certain merge scenarios

### ISSUE THREAD

**Issue by lgreenway** [go-semantic-release/provider-github#5]
Given a commit history such as:

![image](https://user-images.githubusercontent.com/4974093/108904497-8f30be00-75ec-11eb-84b8-b4780c847802.png)

When attempting to perform a semantic release once featureB is merged, the result is:

```
[go-semantic-release]: ci-condition plugin: default@1.2.2
[go-semantic-release]: provider plugin: GitHub@1.5.0
[go-semantic-release]: getting default branch...
[go-semantic-release]: found default branch: master
[go-semantic-release]: repo is private
[go-semantic-release]: found current branch: master
[go-semantic-release]: found current sha: master
[go-semantic-release]: getting latest release...
[go-semantic-release]: found version: 1.1.1
[go-semantic-release]: getting commits...
[go-semantic-release]: analyzing commits...
[go-semantic-release]: commit-analyzer plugin: default@1.3.1
[go-semantic-release]: calculating new version...
[go-semantic-release]: no change
```

I believe this is due to the implementation of [GetCommits](https://github.com/go-semantic-release/provider-github/blob/cc23a5c74cb2dc9afe80115118a50968747abf1e/pkg/provider/github.go#L78) fetching commits chronologically from the current SHA to the last release's SHA instead of fetching the commit differences between the two SHAs, such as the result would be for `git log A...B`.

In the case of a commit history illustrated above, only the featureB merge and `chore:` commits are seen, resulting in the commit-analyzer determining that no change has occurred.

Perhaps the `CompareCommits` API could be used instead?

**Comment by christophwitzko** [comment]
Thank you @lgreenway for reporting this issue and thanks to @jdcole for the fix! 👍 The [v1.5.1](https://github.com/go-semantic-release/provider-github/releases/tag/v1.5.1) release contains the fix.

**Comment by jdcole** [comment]
I think you meant @jdolce for the win!

**Comment by christophwitzko** [comment]
Oops, you are right! 😅  Thanks @jdolce 🙏

**Comment by christophwitzko** [comment]
Hello everyone, it was necessary to revert this fix as it introduces a bug that made it impossible for semantic-release to create the initial release. I will investigate this further, but I am not sure if `CompareCommits` API solves that problem, as it is limited to 250 commits.

**Comment by jdolce** [comment]
@christophwitzko what would you think about adding a config option or flag so we could specify to use `CompareCommits` instead of `ListCommits`? Maybe something like `--provider-opt "compareCommits=true"`

The limitations of `CompareCommits` has never impacted us as we are essentially creating new versions with almost every commit. So the 250 commit limit is not an issue for us.

**Comment by christophwitzko** [comment]
Hey everyone, I just added the `--provider-opt github_use_compare_commits=true` option to enable the compare commits API in version [1.8.0](https://github.com/go-semantic-release/provider-github/releases/tag/v1.8.0). 🙌 
Feel free to test it out and let me know if any issues arise. ☺️
